name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04

    env:
      MIX_ENV: test
      HEX_KEY: ${{ secrets.HEX_KEY }}

    strategy:
      matrix:
        elixir: [ 1.18.4 ]
        otp: [ 27.3.4 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache
        uses: actions/cache@v3
        id: cache 
        with:
          path: |
            deps
            _build
            ~/.cache/rebar3
          key: ${{ runner.os }}_${{ matrix.otp }}_${{ matrix.elixir }}_cache_${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}_${{ matrix.otp }}_${{ matrix.elixir }}_cache_
      - name: Install Mix Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix hex.organization auth doofinder --key $HEX_KEY
          mix deps.get
      - name: Compile dev
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix compile
        env:
          MIX_ENV: dev

      - name: Check warnings
        run: mix compile --warnings-as-errors --no-deps-check
        env:
          MIX_ENV: dev

      - name: Compile test
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix compile
        env:
          MIX_ENV: test

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run credo
        run: mix credo --strict --ignore todo
        env:
          MIX_ENV: dev

      - name: Run Tests
        run: mix test

      - name: Run dialyzer
        run: mix dialyzer
        env:
          MIX_ENV: dev
